version: 2

project_name: preflight

builds:
  - id: preflight
    main: ./main.go
    binary: preflight
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/preflightsh/preflight/cmd.version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

brews:
  - name: preflight
    repository:
      owner: preflightsh
      name: homebrew-preflight
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    description: "Preflight CLI for launch readiness checks"
    homepage: "https://github.com/preflightsh/preflight"
    commit_author:
      name: "GitHub Actions"
      email: "actions@github.com"
    install: |
      bin.install "preflight"

dockers:
  - id: preflight-amd64
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/preflightsh/preflight:{{ .Version }}-amd64"
      - "ghcr.io/preflightsh/preflight:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"

  - id: preflight-arm64
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/preflightsh/preflight:{{ .Version }}-arm64"
      - "ghcr.io/preflightsh/preflight:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/preflightsh/preflight:{{ .Version }}"
    image_templates:
      - "ghcr.io/preflightsh/preflight:{{ .Version }}-amd64"
      - "ghcr.io/preflightsh/preflight:{{ .Version }}-arm64"

  - name_template: "ghcr.io/preflightsh/preflight:latest"
    image_templates:
      - "ghcr.io/preflightsh/preflight:latest-amd64"
      - "ghcr.io/preflightsh/preflight:latest-arm64"

release:
  prerelease: false

changelog:
  disable: true
